Repository Rex2002/sound-investments, pull requests merged in 2023-06, with the labels that each got.

#68 Audio: Dynamic tempo from backings
  src/main/java/app/StateManager.java
  src/main/java/audio/Constants.java
  src/main/java/audio/Sonifier.java
  src/main/java/audio/mixer/Backing.java
  src/main/java/audio/synth/Test.java
Labels: Architecture, Synthesizer, Harmonizer, Mixer

#63 First Mixer implementation
  src/main/java/audio/mixer/Mixer.java
  src/main/java/audio/synth/Test.java
Labels: Mixer

#103 Fix impact sample
  src/main/java/audio/synth/EvInstrEnum.java
  src/main/resources/audio/impacts/CPA_Free_Impact_30.wav
  src/main/resources/audio/impacts/Impact_Bass_0.wav
Labels: Mixer

#111 add one more backing
  src/main/java/audio/mixer/Mixer.java
  src/main/resources/audio/backings/75_4_fill_0_ridge.wav
  src/main/resources/audio/backings/75_4_groove_0_ridge.wav
Labels: Mixer

#146 More api keys
  src/main/java/dataRepo/DataRepo.java
Labels: API/Data

#149 resolve #135
  src/main/java/app/ui/MusicSceneController.java
Labels: UI

#148 Issue #83
  src/main/java/app/StateManager.java
  src/main/java/app/communication/MusicData.java
  src/main/java/app/ui/CommonController.java
  src/main/java/app/ui/MusicSceneController.java
  src/main/java/audio/Sonifier.java
  src/main/java/audio/synth/playback/PlaybackController.java
  src/main/resources/MusicScene.fxml
Labels: UI

#163 resolves #162
  src/main/java/app/ui/MusicSceneController.java
  src/main/java/util/DateUtil.java
Labels: UI

#158 feat(mixer): add two more evInstrs
  src/main/java/audio/Sonifier.java
  src/main/java/audio/mixer/Mixer.java
  src/main/java/audio/synth/EvInstrEnum.java
  src/main/java/audio/synth/EvInstrLine.java
  src/main/resources/audio/impacts/Impact_Bell_0.wav
  src/main/resources/audio/impacts/Impact_Bell_1.wav
Labels: Mixer

#164 feat: addresses #126 (removes location from UI), fixes #147 (adds bac…
  src/main/java/app/ui/MainSceneController.java
  src/main/resources/MainScene.fxml
  src/main/resources/close_icon_w_bg.png
Labels: UI

#161 Reverb fix #144
  src/main/java/audio/harmonizer/Harmonizer.java
  src/main/java/audio/synth/EvInstrEnum.java
  src/main/java/audio/synth/SynthLine.java
  src/main/java/audio/synth/Test.java
  src/main/java/audio/synth/fx/Effect.java
  src/main/resources/audio/impacts/Impact_Bass_0.wav
  src/main/resources/audio/impacts/Impact_Timp_0.wav
Labels: Synthesizer

#167 Fix #129
  src/main/java/app/StateManager.java
  src/main/java/app/communication/MusicData.java
  src/main/java/app/ui/App.java
  src/main/java/app/ui/MainSceneController.java
  src/main/java/app/ui/MusicSceneController.java
  src/main/java/dataAnalyzer/Analyzer.java
  src/main/java/dataAnalyzer/Blur.java
  src/main/java/dataAnalyzer/FlagFormationAnalyzer.java
  src/main/java/dataAnalyzer/FormationAnalyzer.java
  src/main/java/dataAnalyzer/GeneralTrends.java
  src/main/java/dataAnalyzer/Trendbreak.java
  src/main/java/dataAnalyzer/TriangleFormationAnalyzer.java
  src/main/java/dataAnalyzer/VFormationAnalyzer.java
  src/main/java/dataRepo/DataRepo.java
  src/main/resources/Data/etfs.json
  src/main/resources/Data/indices.json
  src/main/resources/Data/og-stocks.json
  src/main/resources/Data/stocks.json
  src/main/resources/TestData/TestDoubles.json
  src/main/resources/TestData/TestFlagPrices.json
  src/main/resources/TestData/TestPrices.json
  src/main/resources/TestData/TestTrianglePrices.json
  src/main/resources/TestData/TestVPrices.json
  src/main/resources/UI/MainScene.fxml
  src/main/resources/UI/MusicScene.fxml
  src/main/resources/UI/back_btn.png
  src/main/resources/UI/choice.css
  src/main/resources/UI/close_icon.png
  src/main/resources/UI/for_btn.png
  src/main/resources/UI/loading.png
  src/main/resources/UI/pause_btn.png
  src/main/resources/UI/play_btn.png
  src/main/resources/UI/stop_btn.png
  src/main/resources/close_icon.png
Labels: API/Data

#182 fix: make pan visible in UI and fix applyPan()
  src/main/java/app/mapping/InstrumentMapping.java
  src/main/java/audio/synth/SynthLine.java
Labels: bug
